<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Services\Crud\BuildInterface\CrudInterface;

/**
 * PasajeroHasRouteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PasajeroHasRouteRepository extends EntityRepository
{

    public function findByRoute($routeId)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT pasajeroHasRoute
            FROM AppBundle:PasajeroHasRoute pasajeroHasRoute
            WHERE
            pasajeroHasRoute.route = :routeId
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('routeId', $routeId);

        return $query->getResult();
    }

}
