<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Services\Crud\BuildInterface\CrudInterface;

/**
 * QuotationMainRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationMainRepository extends EntityRepository
{

//    public function findAll($limit = null, $offset = null)
//    {
//        return $this->findBy(['isActive' => 1], ['id' => 'DESC'], $limit, $offset);
//    }

    public function findAllHas($id)
    {
        $stmt = $this->getEntityManager()
            ->getConnection()
            ->prepare('SELECT * FROM quotation_main_has_quotation WHERE quotation_main_id = :id');
        $stmt->bindValue('id', $id);
        $stmt->execute();
        return $stmt->fetchAll();
    }

    public function findAllByEstado($estado)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT a
            FROM AppBundle:QuotationMain a
            WHERE 
            a.estado = :estado
            ORDER BY a.id DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('estado', $estado);

        return $query->getResult();
    }

}
