<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Services\Crud\BuildInterface\CrudInterface;

/**
 * QuotationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuotationRepository extends EntityRepository
{

//    public function findAll($limit = null, $offset = null)
//    {
//        return $this->findBy(['isActive' => 1], ['id' => 'DESC'], $limit, $offset);
//    }

    public function findOneByEstado($id, $estado)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT a
            FROM AppBundle:Quotation a
            WHERE 
            a.estado = :estado AND
            a.id = :id
            ORDER BY a.id DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('id', $id);
        $query->setParameter('estado', $estado);

        return $query->getOneOrNullResult();
    }

}
