<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Services\Crud\BuildInterface\CrudInterface;

/**
 * QuoteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class QuoteRepository extends EntityRepository implements CrudInterface
{

    public function findAll($limit = null, $offset = null)
    {
        return $this->findBy(['isActive' => 1], ['id' => 'DESC'], $limit, $offset);
    }

    public function findByRequerimientoProduct($requerimientoId, $productId)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT quote
            FROM AppBundle:Quote quote
            INNER JOIN quote.product product
            INNER JOIN quote.requerimiento requerimiento
            WHERE 
            requerimiento.idIncrement = :requerimiento
            ";


//        product.idIncrement = :product AND

        $query = $em->createQuery($dql);
        $query->setParameter('requerimiento', $requerimientoId);
//        $query->setParameter('product', $productId);

        return $query->getResult();
    }

}
