<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Services\Crud\BuildInterface\CrudInterface;

/**
 * RequerimientoHasProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequerimientoHasProductRepository extends EntityRepository
{

    public function findAll($limit = null, $offset = null)
    {
        return $this->findBy([], ['id' => 'DESC'], $limit, $offset);
    }

    public function findAllByRequerimiento($requerimiento)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT obj
            FROM AppBundle:RequerimientoHasProduct obj
            WHERE
            obj.requerimiento = :requerimiento
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('requerimiento', $requerimiento);

        return $query->getResult();
    }

    public function findAllByRequerimientoCotizar($requerimientoId, $productId)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT obj, product
            FROM AppBundle:RequerimientoHasProduct obj
            INNER JOIN obj.product product
            WHERE
            obj.requerimiento = :requerimiento AND 
            product IN (:product)
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('requerimiento', $requerimientoId);
        $query->setParameter('product', [$productId]);

        return $query->getResult();
    }


}
