<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;
use AppBundle\Services\Crud\BuildInterface\CrudInterface;

/**
 * RequerimientoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RequerimientoRepository extends EntityRepository
{

    public function findAll($limit = null, $offset = null)
    {
        return $this->findBy(['isActive' => 1], ['idIncrement' => 'DESC'], $limit, $offset);
    }

    public function findLastOne()
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT requerimiento
            FROM AppBundle:Requerimiento requerimiento
            WHERE
            requerimiento.isActive = :active
            ORDER BY requerimiento.idIncrement DESC
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setMaxResults(1);

        return $query->getOneOrNullResult();
    }

    public function findAllIn($ids)
    {
        $em = $this->getEntityManager();
        $dql = "
            SELECT profile
            FROM AppBundle:Profile profile
            WHERE
            profile.idIncrement IN (:ids) AND
            profile.isActive = :active
            ";

        $query = $em->createQuery($dql);
        $query->setParameter('active', 1);
        $query->setParameter('ids', $ids);

        return $query->getResult();
    }



}
