app_generar_orden_compra_index:
    path:  /
    defaults:
        _controller: AppBundle:GenerarOrdenCompra:index
    methods: [GET]

app_generar_orden_compra_create:
    path:  /create
    defaults:
        _controller: AppBundle:GenerarOrdenCompra:create
    methods: [GET, POST]

app_generar_orden_compra_edit:
    path:  /edit
    defaults:
        _controller: AppBundle:GenerarOrdenCompra:edit
    requirements:
    methods: [POST, PUT]

app_generar_orden_compra_delete:
    path:  /delete
    defaults:
        _controller: AppBundle:GenerarOrdenCompra:delete
    requirements:
    methods: [DELETE]

app_generar_orden_compra_view:
    path:  /view/{id}
    defaults:
        _controller: AppBundle:GenerarOrdenCompra:view
    requirements:
    methods: [GET]

app_generar_orden_compra_info:
    path:  /info
    defaults:
        _controller: AppBundle:GenerarOrdenCompra:info
    requirements:
    methods: [POST]
