app_quotation_lista_cotizacion:
    path:  /lista-cotizacion
    defaults:
        _controller: AppBundle:Quotation:listaCotizacion
    methods: [GET, POST]

app_quotation_lista_ordenes_compra:
    path:  /lista-ordenes-compra
    defaults:
        _controller: AppBundle:Quotation:listaOrdenesCompra
    methods: [GET, POST]

