app_quotation_lista_cotizacion:
    path:  /detalle-cotizacion/{id}
    defaults:
        _controller: AppBundle:Quotation:detalleCotizacion
    methods: [GET, POST]

app_quotation_lista_ordenes_compra:
    path:  /lista-ordenes-compra
    defaults:
        _controller: AppBundle:Quotation:listaOrdenesCompra
    methods: [GET, POST]

