app_quotation_detalle_cotizacion:
    path:  /detalle-cotizacion/{id}
    defaults:
        _controller: AppBundle:Quotation:detalleCotizacion
    methods: [GET, POST]

app_quotation_detalle_ordenes_compra:
    path:  /detalle-ordenes-compra/{id}
    defaults:
        _controller: AppBundle:Quotation:detalleOrdenesCompra
    methods: [GET, POST]

