app_default:
    resource: "@AppBundle/Resources/config/route/default.yml"
    prefix: /

app_security:
    resource: "@AppBundle/Resources/config/route/security.yml"
    prefix: /security

app_categorytree:
    resource: "@AppBundle/Resources/config/route/category-tree.yml"
    prefix: /category-tree

app_product:
    resource: "@AppBundle/Resources/config/route/product.yml"
    prefix: /product

app_user:
    resource: "@AppBundle/Resources/config/route/user.yml"
    prefix: /user

app_role:
    resource: "@AppBundle/Resources/config/route/acl-role.yml"
    prefix: /acl-role

app_profile:
    resource: "@AppBundle/Resources/config/route/profile.yml"
    prefix: /profile

app_categorytreetoassign:
    resource: "@AppBundle/Resources/config/route/category-treetoassign.yml"
    prefix: /category-tree-to-assign

app_chart:
    resource: '@AppBundle/Resources/config/route/chart.yml'
    prefix: /chart

app_generar_requerimiento:
    resource: '@AppBundle/Resources/config/route/generar-requerimiento.yml'
    prefix: /generar-requerimiento

app_despacho_almacen:
    resource: '@AppBundle/Resources/config/route/despacho-almacen.yml'
    prefix: /despacho-almacen

app_recepcion_mercaderia:
    resource: '@AppBundle/Resources/config/route/recepcion-mercaderia.yml'
    prefix: /recepcion-mercaderia

app_invitar_cotizar_proveedores:
    resource: '@AppBundle/Resources/config/route/invitar-cotizar-proveedores.yml'
    prefix: /invitar-cotizar-proveedores

app_cotizar_proveedor:
    resource: '@AppBundle/Resources/config/route/cotizar-proveedor.yml'
    prefix: /cotizar-proveedor

app_buscar_cotizacion:
    resource: '@AppBundle/Resources/config/route/buscar-cotizacion.yml'
    prefix: /buscar-cotizacion

app_generar_orden_compra:
    resource: '@AppBundle/Resources/config/route/generar-orden-compra.yml'
    prefix: /generar-orden-compra

app_quotation:
    resource: '@AppBundle/Resources/config/route/quotation.yml'
    prefix: /quotation

app_quotation_main:
    resource: '@AppBundle/Resources/config/route/quotation-main.yml'
    prefix: /quotation-main

